"""New Migration

Revision ID: 001c0c41c5a0
Revises: 6cfa3efcb740
Create Date: 2022-01-22 18:20:23.141251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001c0c41c5a0'
down_revision = '6cfa3efcb740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
